version: '3'
services:
  sidewinder_mysql:
    image: mysql:5.7
    container_name: sidewinder_mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: sidewinder
    ports:
      - 127.0.0.1:$SIDEWINDER_MYSQL_PORT:3306
  #################### Base  ####################

  base: &base
    image: darthjee/sidewinder
    volumes:
      - ./source:/home/app/app
    links:
      - sidewinder_mysql:mysql
    env_file: .env


  base_build:
    <<: *base
    build:
      context: .
      dockerfile: Dockerfile.sidewinder
    command: echo done

  #################### CONTAINERS ####################

  sidewinder_app:
    <<: *base
    container_name: sidewinder_app
    command: /bin/bash bin/server.sh
    depends_on: [base_build]
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - RAILS_ENV=development
      - SIDEWINDER_MYSQL_PORT=3306

  sidewinder_tests:
    <<: *base
    container_name: sidewinder_tests
    command: /bin/bash bin/tests.sh
    depends_on: [base_build]
    environment:
      - RAILS_ENV=test

  sidewinder_root:
    <<: *base
    user: root
    container_name: sidewinder_root
    command: /bin/bash
    depends_on: [base_build]

  sidewinder_production:
    env_file: .env.production
    container_name: sidewinder_production
    image: darthjee/production_sidewinder
    build:
      context: .
      dockerfile: Dockerfile.production_sidewinder
